export const items = [
	{
		id: 1,
		name: 'Product-1',
		price: 9.99,
		img: "../../images/1.jpg",
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['Black', 'DarkBlue', 'Blue', 'LightBlue'],
	},
	{
		id: 2,
		name: 'Product-2',
		price: 5.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['DarkRed', 'Maroon', 'FireBrick', 'Red', 'Crimson'],
	},
	{
		id: 3,
		name: 'Product-3',
		price: 19.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['SeaGreen', 'SpringGreen', 'Turquoise', 'Teal', 'SlateBlue', 'RoyalBlue'],
	},
	{
		id: 4,
		name: 'Product-4',
		price: 1.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 5,
		name: 'Product-5',
		price: 14.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 6,
		name: 'Product-6',
		price: 16.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 7,
		name: 'Product-7',
		price: 11.99,
		img: './images/1.jpg',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 8,
		name: 'Product-8',
		price: 18.49,
		img: 'https://picsum.photos/362/301',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 9,
		name: 'Product-9',
		price: 21.99,
		img: 'https://picsum.photos/361/304',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 10,
		name: 'Product-10',
		price: 24.99,
		img: 'https://picsum.photos/362/300',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 11,
		name: 'Product-11',
		price: 29.99,
		img: 'https://picsum.photos/361/304',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 12,
		name: 'Product-12',
		price: 0.99,
		img: 'https://picsum.photos/362/300',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
]
