export const items = [
	{
		id: 1,
		name: 'Product-1',
		price: 9.99,
		img: 'https://picsum.photos/360/300',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['Black', 'DarkBlue', 'Blue', 'LightBlue'],
	},
	{
		id: 2,
		name: 'Product-2',
		price: 5.99,
		img: 'https://picsum.photos/361/300',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['DarkRed', 'Maroon', 'FireBrick', 'Red', 'Crimson'],
	},
	{
		id: 3,
		name: 'Product-3',
		price: 19.99,
		img: 'https://picsum.photos/361/302',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['SeaGreen', 'SpringGreen', 'Turquoise', 'Teal', 'SlateBlue', 'RoyalBlue'],
	},
	{
		id: 4,
		name: 'Product-4',
		price: 1.99,
		img: 'https://picsum.photos/361/303',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 5,
		name: 'Product-5',
		price: 14.99,
		img: 'https://picsum.photos/361/304',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 6,
		name: 'Product-6',
		price: 16.99,
		img: 'https://picsum.photos/362/300',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
]
