export const items = [
	{
		id: 1,
		name: 'Product-1',
		price: 9.99,
		img: 'https://picsum.photos/360/500',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['black', 'darkblue', 'blue', 'lightblue'],
	},
	{
		id: 2,
		name: 'Product-2',
		price: 5.99,
		img: 'https://picsum.photos/361/500',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['darkred', 'maroon', 'firebrick', 'red', 'crimson'],
	},
	{
		id: 3,
		name: 'Product-3',
		price: 19.99,
		img: 'https://picsum.photos/361/502',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['SeaGreen', 'SpringGreen', 'Turquoise', 'Teal', 'SlateBlue', 'RoyalBlue'],
	},
	{
		id: 4,
		name: 'Product-4',
		price: 1.99,
		img: 'https://picsum.photos/361/503',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 5,
		name: 'Product-5',
		price: 14.99,
		img: 'https://picsum.photos/361/500',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
	{
		id: 6,
		name: 'Product-6',
		price: 16.99,
		img: 'https://picsum.photos/361/500',
		sizes: ['XS', 'S', 'M', 'L', 'XL'],
		colors: ['red', 'green', 'blue', 'orange'],
	},
]
